JAVA = $(JAVA_HOME)/bin/java
CFLAGS+= -DWIN32 -DBZ_STATIC_LIB ${DBGFLAGS}
CXXFLAGS+= -DWIN32 -DBZ_STATIC_LIB ${DBGFLAGS}
INCDIR+= -I$(BLITZ_HOME)/include
LIBS+= $(BLITZ_HOME)/lib/libblitz.a ../lowlevel/libal.lib

ifeq ("yes","$(strip $(IMAS_MDSPLUS))")
LIBS+= -L$(MDSPLUS_DIR)/lib
LIBS+= $(MDSPLUS_DIR)/lib/XTreeShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsObjectsCppShr.a
LIBS+= $(MDSPLUS_DIR)/lib/TdiShr.a
LIBS+= $(MDSPLUS_DIR)/lib/TreeShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsIpShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsShr.a
LIBS+= -lxml2 -lws2_32 -ldl -liphlpapi
endif # IMAS_MDSPLUS

ifeq ("yes","$(strip $(IMAS_UDA))")
ifeq ("yes","$(strip $(IMAS_UDAFAT))")
LIBS+= -L$(UDA_HOME)/lib
LIBS+= $(UDA_HOME)/lib/libfatuda_cpp.a
LIBS+= $(UDA_HOME)/lib/libportablexdr.a
LIBS+= $(PostgresSQL_ROOT)/lib/libpq.a
LIBS+= -lws2_32 -lssl -lcrypto -lxml2
else
LIBS+= -L$(UDA_HOME)/lib
LIBS+= $(UDA_HOME)/lib/libuda_cpp.a
LIBS+= $(UDA_HOME)/lib/libportablexdr.a
LIBS+= -lws2_32 -lssl -lcrypto
endif
endif # IMAS_UDA

ifeq ("yes","$(strip $(IMAS_HDF5))")
LIBS+= -L$(HDF5_HOME)/lib
LIBS+= $(HDF5_HOME)/lib/libhdf5.a -ldl -lz -lboost_filesystem-mt -lboost_system-mt
endif # IMAS_HDF5

# Check existence of the "indent" utility to get a clean C format
ifeq "$(shell which indent 2> /dev/null)" ""
BEAUTIFY = echo
else
BEAUTIFY = indent -kr --no-tabs -l1000
endif

TARGETS = $(addprefix $(LIB_DIR)/,libal-cpp.lib libal-cpp.dll)

all: $(SOURCES) $(TARGETS) id_cpp_all

$(LIB_DIR) $(BUILD_DIR) $(libdir) $(includedir)/ids $(datadir)/src/cppinterface/ids:
	$(mkdir_p) $@

# Windows dynamic library
$(LIB_DIR)/libal-cpp.dll: $(OBJ_FILES) $(IDS_OBJ_FILES) | $(LIB_DIR)
	$(CXX) $(LDFLAGS) -o $@ -shared -Wl,$(SONAME_OPT),$(@F).$(SO_NUM) -Wl,--out-implib,$@.lib $^ $(LIBS)

# Windows static library
$(LIB_DIR)/libal-cpp.lib: $(OBJ_FILES) $(IDS_OBJ_FILES) | $(LIB_DIR)
	$(AR) rcvsu $@ $^
	ranlib $@

install: all pkgconfig_install id_cpp_install
	$(mkdir_p) $(packagedir)/cppinterface/lib
	$(mkdir_p) $(packagedir)/cppinterface/include/ids
	$(mkdir_p) $(packagedir)/blitz/lib
	# Copy libraries
	for OBJECT in `find . -type f \( -name "*.lib" -or -name "*.dll" \)`; do \
		$(CP) $$OBJECT $(packagedir)/cppinterface/lib; \
	done
	# Copy Blitz libraries
	$(CP) $(BLITZ_HOME)/lib/libblitz.a $(packagedir)/blitz/lib
	# Copy includes
	$(CP) $(SRC_DIR)/*.h $(packagedir)/cppinterface/include
	$(CP) $(IDS_SRC_DIR)/*.h $(packagedir)/cppinterface/include/ids

uninstall: pkgconfig_uninstall id_cpp_uninstall

sources_install: $(SOURCES)
sources_uninstall:
