ifeq "$(strip $(CC))" "icc"
CXX=icpc
CXXFLAGS= -O0 -fPIC -shared-intel ${DBGFLAGS}
LDFLAGS=
else
CXX=g++
CXXFLAGS=-std=c++11 -pthread -O2 -Wa,-mbig-obj -fPIC ${DBGFLAGS}
LDFLAGS=-pthread
endif

INCDIR= -I$(BLITZ_HOME)/include -I$(UAL_BUILD)/lowlevel -I$(UAL_BUILD)/cppinterface/src
LIBS= -L$(BLITZ_HOME)/lib -L$(UAL_BUILD)/lowlevel -L$(UAL_BUILD)/cppinterface/lib
LIBS+= $(UAL_BUILD)/cppinterface/lib/libal-cpp.lib $(UAL_BUILD)/lowlevel/libal.lib
LIBS+= $(BLITZ_HOME)/lib/libblitz.a
BINOUT=TestSuite.exe
CFLAGS+= -DWIN32 -DBZ_STATIC_LIB
CXXFLAGS+= -DWIN32 -DBZ_STATIC_LIB

ifeq ("yes","$(strip $(IMAS_MDSPLUS))")
LIBS+= -L$(MDSPLUS_DIR)/lib
LIBS+= $(MDSPLUS_DIR)/lib/XTreeShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsObjectsCppShr.a
LIBS+= $(MDSPLUS_DIR)/lib/TdiShr.a
LIBS+= $(MDSPLUS_DIR)/lib/TreeShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsIpShr.a
LIBS+= $(MDSPLUS_DIR)/lib/MdsShr.a
LIBS+= -lxml2 -lws2_32 -ldl -liphlpapi
endif # IMAS_MDSPLUS

ifeq ("yes","$(strip $(IMAS_UDA))")
ifeq ("fat","$(strip $(IMAS_UDA))")
LIBS+= -L$(UDA_HOME)/lib
LIBS+= $(UDA_HOME)/lib/libfatuda_cpp.a
LIBS+= $(UDA_HOME)/lib/libportablexdr.a
LIBS+= $(PostgresSQL_ROOT)/lib/libpq.a
LIBS+= -lws2_32 -lssl -lcrypto -lxml2
else
LIBS+= -L$(UDA_HOME)/lib
LIBS+= $(UDA_HOME)/lib/libuda_cpp.a
LIBS+= $(UDA_HOME)/lib/libportablexdr.a
LIBS+= -lws2_32 -lssl -lcrypto
endif
endif # IMAS_UDA

ifeq ("yes","$(strip $(IMAS_HDF5))")
LIBS+= -L$(HDF5_HOME)/lib
LIBS+= $(HDF5_HOME)/lib/libhdf5.a -ldl -lz
endif # IMAS_HDF5
