
# Please do not run make on this file directly.
ifeq (1,$(words $(MAKEFILE_LIST)))
  $(error Do not run make on this file directly, use Makefile or Makefile-ext)
endif

# Require explicit target, do not assume make all
help:
	$(error Specify a target to run, e.g. make check)

TESTS = cpp_tests
GENSOURCES = TestSuite.cpp
TMP_DIR=./tmp

.PHONY: check clean clean-src
all: $(BINOUT)
sources: $(GENSOURCES)
sources_install:
sources_uninstall:
install:
uninstall:
clean:
	$(RM) *.log *.o $(BINOUT)
clean-src: clean
	$(RM) $(GENSOURCES)
check test: $(TESTS)


#  BUILD
$(BINOUT): helper.o TestSuite.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LIBDIR) $(LIBS)
.SUFFIXES:.cpp
.cpp.o:
	$(CXX) $(INCDIR) $(CXXFLAGS) -c $< -o $@

#  SOURCE GENERATION
.PHONY: TestSuite.cpp
TestSuite.cpp: %.cpp:%.xsl | $(IDSDEF)
	xsltproc --stringparam mdsplus_backend $(IMAS_MDSPLUS) --stringparam hdf5_backend $(IMAS_HDF5) --stringparam uda_backend $(IMAS_UDA) \
		$< $| > $@

# RUN TESTS
# Create dirs as needed
$(TMP_DIR):
	$(mkdir_p) $@

# Canned recipe that runs prerequisites as tests and produces TAP-like output
define run-tests
	@( \
	echo 1..$(words $^) \# Tests: $(^F) ;\
	N=1;for prog in $^ ;do \
	 ( $(test_ENV) ./$$prog 2>&1 | tee ./$$prog.log ) && \
	 test 0 -eq $$(grep -c -i error ./$$prog.log ) && \
	 echo ok $$N - $$prog passed. || echo not ok $$N - $$prog failed. ;\
	done \
	) | tee $@.log
	@test 0 -eq $$(grep -c -i error $@.log) || exit 1
endef

cpp_tests: $(BINOUT) | $(TMP_DIR)
	$(run-tests)
