ifeq "$(strip $(CC))" "icc"
CXX=icpc
CXXFLAGS=-g -O0 -fPIC -shared-intel
LDFLAGS=-g
else
CXX=g++
CXXFLAGS=-std=c++11 -pthread -g -O0 -D__USE_XOPEN2K8 -fPIC
LDFLAGS=-g -pthread
endif

INCDIR=`pkg-config blitz --cflags` -I$(AL_BUILD)/cppinterface/src -I$(AL_BUILD)/lowlevel
LIBS=-L$(AL_BUILD)/cppinterface/lib -L$(AL_BUILD)/lowlevel
LIBS+=-lal-cpp -lal `pkg-config blitz --libs`
